### ISSUE TITLE
extra money swgm

### ISSUE THREAD

**Issue by lazhoroni** [SomethingFromSomewhere/SWGM#3]
https://github.com/lazhoroni/SWGM/blob/master/scripting/swgm_para.sp
Don't let the first 3 rounds give you extra money. the next rounds give extra money.
I wanted to do it this way. But I get the error and it doesn't work. Do you want to help_?
L 03/06/2019 - 22:57:46: SourceMod error session started L 03/06/2019 - 22:57:46: Info (map "de_dust2") (file "errors_20190306.log") L 03/06/2019 - 22:57:46: Failed to auto generate config for SWGM.smx, make sure the directory has write permission.

**Comment by lazhoroni** [comment]
L 03/06/2019 - 23:19:28: Error log file session closed.
L 03/06/2019 - 23:19:29: SourceMod error session started
L 03/06/2019 - 23:19:29: Info (map "de_dust2") (file "errors_20190306.log")
L 03/06/2019 - 23:19:29: Failed to auto generate config for SWGM.smx, make sure the directory has write permission.
L 03/06/2019 - 23:20:33: [SM] Exception reported: [InGroup] Client index 1 is not validated.
L 03/06/2019 - 23:20:33: [SM] Blaming: SWGM.smx
L 03/06/2019 - 23:20:33: [SM] Call stack trace:
L 03/06/2019 - 23:20:33: [SM]   [0] ThrowNativeError
L 03/06/2019 - 23:20:33: [SM]   [1] Line 195, C:\Users\User\Desktop\sourcemod++\addons\sourcemod\scripting\SWGM.sp::CheckClient
L 03/06/2019 - 23:20:33: [SM]   [2] Line 156, C:\Users\User\Desktop\sourcemod++\addons\sourcemod\scripting\SWGM.sp::Native_InGroup
L 03/06/2019 - 23:20:33: [SM]   [4] SWGM_InGroup
L 03/06/2019 - 23:20:33: [SM]   [5] Line 78, C:\Users\User\Desktop\sourcemod++\addons\sourcemod\scripting\swgm_para.sp::lazRoundStart

**Comment by SomethingFromSomewhere** [comment]
https://github.com/lazhoroni/SWGM/blob/232f984d6ff59f94aa6359ef68c37ff57e3253ab/scripting/swgm_para.sp#L55

Change IsClientInGame to SWGM_IsPlayerValidated.

**Comment by lazhoroni** [comment]
```
L 03/07/2019 - 01:00:57: SourceMod error session started
L 03/07/2019 - 01:00:57: Info (map "de_dust2") (file "errors_20190307.log")
L 03/07/2019 - 01:00:57: Failed to auto generate config for SWGM.smx, make sure the directory has write permission.
```

dude, how can i fix this error?

**Comment by SomethingFromSomewhere** [comment]
Create directory "swgm" in "cfg/sourcemod".

**Comment by lazhoroni** [comment]
thank you for everything.

**Comment by lazhoroni** [comment]
`L 03/07/2019 - 01:17:02: SourceMod error session started
L 03/07/2019 - 01:17:02: Info (map "de_dust2") (file "errors_20190307.log")
L 03/07/2019 - 01:17:02: [SM] Exception reported: Language phrase "OdulDuyurusu" not found (arg 4)
L 03/07/2019 - 01:17:02: [SM] Blaming: swgm_para.smx
L 03/07/2019 - 01:17:02: [SM] Call stack trace:
L 03/07/2019 - 01:17:02: [SM]   [0] VFormat
L 03/07/2019 - 01:17:02: [SM]   [1] Line 70, C:\Users\User\Desktop\sourcemod++\addons\sourcemod\scripting\include\multicolors.inc::CPrintToChat
L 03/07/2019 - 01:17:02: [SM]   [2] Line 69, C:\Users\User\Desktop\sourcemod++\addons\sourcemod\scripting\swgm_para.sp::lazRoundStart
L 03/07/2019 - 01:19:17: [SM] Exception reported: Language phrase "OdulDuyurusu" not found (arg 4)
L 03/07/2019 - 01:19:17: [SM] Blaming: swgm_para.smx
L 03/07/2019 - 01:19:17: [SM] Call stack trace:
L 03/07/2019 - 01:19:17: [SM]   [0] VFormat
L 03/07/2019 - 01:19:17: [SM]   [1] Line 70, C:\Users\User\Desktop\sourcemod++\addons\sourcemod\scripting\include\multicolors.inc::CPrintToChat
L 03/07/2019 - 01:19:17: [SM]   [2] Line 69, C:\Users\User\Desktop\sourcemod++\addons\sourcemod\scripting\swgm_para.sp::lazRoundStart
L 03/07/2019 - 01:19:18: [SM] Exception reported: Language phrase "Ilk3RoundMesaji" not found (arg 4)
L 03/07/2019 - 01:19:18: [SM] Blaming: swgm_para.smx
L 03/07/2019 - 01:19:18: [SM] Call stack trace:
L 03/07/2019 - 01:19:18: [SM]   [0] VFormat
L 03/07/2019 - 01:19:18: [SM]   [1] Line 70, C:\Users\User\Desktop\sourcemod++\addons\sourcemod\scripting\include\multicolors.inc::CPrintToChat
L 03/07/2019 - 01:19:18: [SM]   [2] Line 84, C:\Users\User\Desktop\sourcemod++\addons\sourcemod\scripting\swgm_para.sp::lazRoundStart
L 03/07/2019 - 01:19:25: [SM] Exception reported: Language phrase "Ilk3RoundMesaji" not found (arg 4)
L 03/07/2019 - 01:19:25: [SM] Blaming: swgm_para.smx
L 03/07/2019 - 01:19:25: [SM] Call stack trace:
L 03/07/2019 - 01:19:25: [SM]   [0] VFormat
L 03/07/2019 - 01:19:25: [SM]   [1] Line 70, C:\Users\User\Desktop\sourcemod++\addons\sourcemod\scripting\include\multicolors.inc::CPrintToChat
L 03/07/2019 - 01:19:25: [SM]   [2] Line 84, C:\Users\User\Desktop\sourcemod++\addons\sourcemod\scripting\swgm_para.sp::lazRoundStart
L 03/07/2019 - 01:19:26: [SM] Exception reported: Language phrase "Ilk3RoundMesaji" not found (arg 4)
L 03/07/2019 - 01:19:26: [SM] Blaming: swgm_para.smx
L 03/07/2019 - 01:19:26: [SM] Call stack trace:
L 03/07/2019 - 01:19:26: [SM]   [0] VFormat
L 03/07/2019 - 01:19:26: [SM]   [1] Line 70, C:\Users\User\Desktop\sourcemod++\addons\sourcemod\scripting\include\multicolors.inc::CPrintToChat
L 03/07/2019 - 01:19:26: [SM]   [2] Line 84, C:\Users\User\Desktop\sourcemod++\addons\sourcemod\scripting\swgm_para.sp::lazRoundStart
L 03/07/2019 - 01:21:10: [SM] Exception reported: Language phrase "OdulDuyurusu" not found (arg 4)
L 03/07/2019 - 01:21:10: [SM] Blaming: swgm_para.smx
L 03/07/2019 - 01:21:10: [SM] Call stack trace:
L 03/07/2019 - 01:21:10: [SM]   [0] VFormat
L 03/07/2019 - 01:21:10: [SM]   [1] Line 70, C:\Users\User\Desktop\sourcemod++\addons\sourcemod\scripting\include\multicolors.inc::CPrintToChat
L 03/07/2019 - 01:21:10: [SM]   [2] Line 69, C:\Users\User\Desktop\sourcemod++\addons\sourcemod\scripting\swgm_para.sp::lazRoundStart
L 03/07/2019 - 01:21:11: [SM] Exception reported: Language phrase "Ilk3RoundMesaji" not found (arg 4)
L 03/07/2019 - 01:21:11: [SM] Blaming: swgm_para.smx
L 03/07/2019 - 01:21:11: [SM] Call stack trace:
L 03/07/2019 - 01:21:11: [SM]   [0] VFormat
L 03/07/2019 - 01:21:11: [SM]   [1] Line 70, C:\Users\User\Desktop\sourcemod++\addons\sourcemod\scripting\include\multicolors.inc::CPrintToChat
L 03/07/2019 - 01:21:11: [SM]   [2] Line 84, C:\Users\User\Desktop\sourcemod++\addons\sourcemod\scripting\swgm_para.sp::lazRoundStart
`

The plugin is running. but these errors occur. Can you help me again?
